### PR TITLE
Notification.find, Notification.find_all and Subscription.count

### LINKED ISSUE #3: Getting notification data
It would be nice if the library allowed getting notification data via the `GET /notifications/NOTIFICATION_ID` REST API endpoint. In particular, this would be useful to get statistics data like `successfully_sent_count` or `open_count`.

I could imagine the following interface based on a `find` method and further attribute readers.

```ruby
notification = Pushpad::Notification.find(id)
notification.open_count # => 4
```
Then it would probably make sense to store the attributes that are currently the return value of `deliver_to`:
```ruby
notification = Pushpad::Notification.new({
  body: "Hello world!",
  title: "Website Name"
})

notification.deliver_to(user)
notification.id # => 1000
notification.scheduled_count #=> 10
```
One thing to consider here is that the `Notification` class currently is more like a notification factory or builder. Calling `deliver_to` multiple times creates multiple notifications with different ids. I'm not sure if this is an edge case that should just be ignored by overwriting the `id` attribute in this case. Alternatively, one could raise an error when `deliver_to` is called and an `id` is already present, but that would be a breaking change to the API.

To circumvent this issue, we could also consider adding a whole new class, e.g. `DeliveredNotification`, which provides the `find` and reader methods. That way the concerns of delivering notifications and getting data about past notifications would be separated cleanly. `deliver_to` could even return a `DeliveredNotification` which could implement `[]` to stay compatible with the prior hashed based API.

### PR DESCRIPTION
**Pull request by tf**
fixes #3, #4 

So here is my first stab at the new features. I've put them in a single PR for now since the changes sort of build on one another, but I'm happy to split things up if you prefer. The first two commits move the notification code from `pushpad{,_spec}.rb` to `pushpad/notification{,_spec}.rb`. So you might want to look at the individual commits to get more meaningful diffs.

I've moved some of the request handling logic from the `Notification` class into a new `Pushpad::Request` module so it can be reused by `Subscription` and other future classes. 

I've tested the new features on the console. But I'd say, let me build my app against my fork for now to find further errors that might have gone unnoticed so far.

Looking forward to your feedback.

Tim

### CODE REVIEW

**Comment by collimarco** [comment]
Hi Tim!

I've reviewed your commits and it's a really great job! Thanks!!

I can merge it right now. However if you prefer to test it in your app first I'll wait.

**Comment by tf** [comment]
Great! Then just give me one or two more days to use the new features and then it can be merged. Is it ok if it stays a single PR that adds both features? Do you want me to add a changelog file?

**Comment by collimarco** [comment]
No, don't worry, there's no changelog at the moment and you don't need to split the PR (I'll rebase without squash).

**Comment by tf** [comment]
Ok, so my tests were quite successful - except for finding out that I did not develop what I need ;) So what I really want is to get data for multiple notifications at once. So I added another commit which adds a `Notification.find_all` method. Please have a look if you want any changes.

Finally, I noticed that using the presence of an `id` option as the condition for making a notification read only, might break existing code. For example, even my own code passed an `id` to `Notification.new` which was ignored so far. Now it resulted in a read only notification. I think this is not desirable and I will look for another way to make `find`/`find_all` return read only notifications.

**Comment by collimarco** [comment]
> Ok, so my tests were quite successful - except for finding out that I did not develop what I need ;) 

Ok :)

> I think this is not desirable and I will look for another way to make find/find_all return read only notifications.

What about initialize the notification normally (without readonly) and then call `readonly!` (inside the  finder method)?

**Comment by tf** [comment]
Good idea. I made the change. If there is nothing else you want to see changed, merging is fine by me now.

**Comment by collimarco** [comment]
Thank you ;) also for the good test coverage and refactoring!

I've merged the pull request and published the gem v. 0.6.0

**Pull request merged**
